# Generated by Django 5.1.6 on 2025-03-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='chama_type',
            field=models.CharField(choices=[('merry_go_round', 'Merry-Go-Round'), ('investment', 'Investment'), ('both', 'Both')], default='merry_go_round', max_length=20),
        ),
    ]
