# Generated by Django 5.1.6 on 2025-03-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0005_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
