# Generated by Django 5.1.6 on 2025-04-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chama',
            name='chama_type',
            field=models.CharField(choices=[('merry_go_round', 'Merry-Go-Round'), ('investment', 'Investment'), ('hybrid', 'Hybrid')], default='', max_length=20),
        ),
    ]
