# Generated by Django 5.1.6 on 2025-04-03 20:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0008_alter_chama_chama_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chama',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Chamas'},
        ),
        migrations.AlterModelOptions(
            name='chamamember',
            options={'ordering': ['joined_at']},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-date_requested']},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='chamamember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chamamember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mpesa_receipt_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='chama',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='chama',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chama',
            name='meeting_day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='date_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HIFACHAMA.chama'),
        ),
        migrations.AddField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chama',
            name='chama_type',
            field=models.CharField(choices=[('merry_go_round', 'Merry-Go-Round'), ('investment', 'Investment'), ('hybrid', 'Hybrid')], default='merry_go_round', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamamember',
            name='chama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='HIFACHAMA.chama'),
        ),
        migrations.AlterField(
            model_name='chamamember',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='chamamember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chama_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='+254700000000', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('chairperson', 'Chairperson'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('repaid', 'Repaid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='chama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='HIFACHAMA.chama'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='HIFACHAMA.chamamember'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('dividend', 'Dividend'), ('expense', 'Expense')], max_length=15),
        ),
    ]
