# Generated by Django 5.1.6 on 2025-04-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0011_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('monthly_dues', 'Monthly Dues'), ('emergency_fund', 'Emergency Fund'), ('project_fund', 'Project Fund'), ('other', 'Other')], max_length=30)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_details', to='HIFACHAMA.transaction')),
            ],
        ),
    ]
