# Generated by Django 5.1.6 on 2025-04-30 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0015_alter_loan_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_create_chama', 'Can create Chama'), ('can_approve_loans', 'Can approve loans'), ('can_add_members', 'Can add new members'), ('can_approve_withdrawals', 'Can approve withdrawals'), ('can_approve_contributions', 'Can approve contributions'), ('can_schedule_meetings', 'Can schedule meetings'), ('can_send_notifications', 'Can send notifications')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customuser_chamas', to='HIFACHAMA.chama'),
        ),
        migrations.AlterField(
            model_name='chamamember',
            name='chama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamamember_chamas', to='HIFACHAMA.chama'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('chairperson', 'Chairperson'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paybill_number', models.CharField(blank=True, max_length=20, null=True)),
                ('till_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(null=True, blank=True, auto_now_add=True)),
                ('chama', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HIFACHAMA.chama')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
