# Generated by Django 5.1.6 on 2025-04-30 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0016_alter_customuser_options_customuser_chama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='chamas', to=settings.AUTH_USER_MODEL),
        ),
    ]
