# Generated by Django 5.1.6 on 2025-05-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0019_alter_loan_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chama',
            name='meeting_day',
        ),
    ]
