# Generated by Django 5.1.6 on 2025-05-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0020_remove_chama_meeting_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='meeting_day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20),
        ),
    ]
