# Generated by Django 5.1.6 on 2025-05-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0021_chama_meeting_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='chama',
        ),
    ]
