# Generated by Django 5.1.6 on 2025-05-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0022_alter_customuser_options_remove_customuser_chama'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customuser_chamas', to='HIFACHAMA.chama'),
        ),
    ]
