# Generated by Django 5.1.6 on 2025-05-02 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0025_rename_phone_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 9, 18, 27, 311072, tzinfo=datetime.timezone.utc)),
        ),
    ]
