# Generated by Django 5.1.6 on 2025-05-02 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0029_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 13, 23, 57, 398607, tzinfo=datetime.timezone.utc)),
        ),
    ]
