# Generated by Django 5.1.6 on 2025-05-02 14:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0031_alter_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chama',
            name='type',
        ),
        migrations.AddField(
            model_name='chama',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamas_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chama',
            name='chama_type',
            field=models.CharField(choices=[('investment', 'Investment'), ('merry_go_round', 'Merry-Go-Round'), ('hybrid', 'Hybrid')], default='hybrid', max_length=50),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 15, 7, 42, 129525, tzinfo=datetime.timezone.utc)),
        ),
    ]
