# Generated by Django 5.1.6 on 2025-05-02 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0032_remove_chama_type_chama_admin_chama_chama_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 15, 8, 20, 278077, tzinfo=datetime.timezone.utc)),
        ),
    ]
