# Generated by Django 5.1.6 on 2025-05-02 20:17

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0034_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='members',
            field=models.ManyToManyField(related_name='chamas', through='HIFACHAMA.ChamaMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 21, 17, 7, 461536, tzinfo=datetime.timezone.utc)),
        ),
    ]
