# Generated by Django 5.1.6 on 2025-05-03 17:35

import HIFACHAMA.models.transactions
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0038_alter_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='member',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 3, 18, 35, 3, 233909, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(choices=[('contribution', 'Contribution'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('member', models.ForeignKey(default=HIFACHAMA.models.transactions.get_default_member, on_delete=django.db.models.deletion.CASCADE, to='HIFACHAMA.chamamember')),
            ],
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
