# Generated by Django 5.1.6 on 2025-05-03 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0039_remove_withdrawal_member_alter_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reason',
            new_name='transaction_type',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 3, 21, 13, 32, 179202, tzinfo=datetime.timezone.utc)),
        ),
    ]
