# Generated by Django 5.1.6 on 2025-05-03 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0040_rename_reason_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 3, 22, 58, 49, 241967, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chama_id', models.IntegerField()),
                ('member_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('cycle_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'HIFACHAMA_rotation',
                'unique_together': {('chama_id', 'position', 'cycle_date')},
            },
        ),
    ]
