# Generated by Django 5.1.6 on 2025-05-03 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0041_alter_otp_expires_at_rotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chama_id', models.IntegerField(unique=True)),
                ('rotational_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('investment_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'HIFACHAMA_balance',
            },
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 3, 23, 2, 44, 410310, tzinfo=datetime.timezone.utc)),
        ),
    ]
