# Generated by Django 5.1.6 on 2025-05-04 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0042_balance_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotation',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rotation',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 9, 38, 11, 527133, tzinfo=datetime.timezone.utc)),
        ),
    ]
