# Generated by Django 5.1.6 on 2025-05-04 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0043_rotation_payout_amount_rotation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 11, 23, 10, 243582, tzinfo=datetime.timezone.utc)),
        ),
    ]
