# Generated by Django 5.1.6 on 2025-05-04 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0044_alter_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='description',
        ),
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(default='No agenda provided'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 17, 33, 35, 345796, tzinfo=datetime.timezone.utc)),
        ),
    ]
