# Generated by Django 5.1.6 on 2025-05-04 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0045_remove_meeting_description_meeting_agenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='penalty_type',
            field=models.CharField(blank=True, choices=[('amount', 'Fixed Amount'), ('percentage', 'Percentage')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='penalty_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_schedule',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 17, 56, 14, 139512, tzinfo=datetime.timezone.utc)),
        ),
    ]
