# Generated by Django 5.1.6 on 2025-05-04 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0046_loan_penalty_type_loan_penalty_value_loan_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 18, 9, 51, 244259, tzinfo=datetime.timezone.utc)),
        ),
    ]
