# Generated by Django 5.1.6 on 2025-05-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0048_loan_approval_date_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chama_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='chama_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
