# Generated by Django 5.1.6 on 2025-05-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0049_customuser_chama_id_customuser_chama_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rotation',
            unique_together={('chama_id', 'cycle_date')},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='purpose',
        ),
        migrations.AddField(
            model_name='rotation',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='monthly', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rotation',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='rotation',
            name='position',
        ),
    ]
