# Generated by Django 5.1.6 on 2025-05-28 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIFACHAMA', '0050_alter_rotation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotation',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='HIFACHAMA.chamamember'),
        ),
    ]
